apiVersion: v1
kind: Secret
metadata:
  name: seguros-secrets
  namespace: seguros
type: Opaque
stringData:
  db-username: quarkus
  db-password: quarkus
  keycloak-admin: admin
  keycloak-admin-password: admin